import { useState } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { HelpCircle, Search, Sparkles, Plus, Minus } from 'lucide-react';

interface FAQSectionProps {
  isDarkMode: boolean;
}

const FAQS = [
  {
    q: 'How does the Aura Liability Shield protect my company?',
    a: 'When using our Employer of Record (EoR) or localized employee nodes, Aura serves as the legal employer of record on local papers. This means we take 100% of the statutory employment liability, ensuring localized labor contract adherence, accurate local pension schemes, benefit claims validation, and tax payment compliance.',
    category: 'Security & Legal'
  },
  {
    q: 'What is the "Neuro-Schema" or "Active Schema" layer?',
    a: 'Active schemas are our automated legal datasets that map real-time regional labor standards (e.g. EU Working Time Directives, localized retirement accounts) directly to digital payroll routing rules. If a regional legislature updates overtime guidelines, the active schema immediately recalculates compliance values for you.',
    category: 'Technology'
  },
  {
    q: 'Are contract formats and payouts compliant with independent tax authorities?',
    a: 'Yes. All contracts generated by Compliance Sentry meet regional standards for self-employed/independent classifications, avoiding misclassification penalties. Payouts are routed directly as clean local accounts transfers, compliant with IRS, HMRC, and EEA rules.',
    category: 'Billing & Payouts'
  },
  {
    q: 'How long does a localized entity installation take?',
    a: 'Using Aura’s EOR node, you can onboarding and launch compliance shielding for full-time hires in new countries within 48 hours. If you wish to set up standard custom sub-entities, our guide rails reduce normal multi-month timelines down to 2-3 weeks.',
    category: 'Onboarding'
  },
  {
    q: 'Can we integrate custom tools like Slack or Figma into worker databases?',
    a: 'Absolutely. Aura provides API endpoints and webhooks. Our dashboard even supports real-time synchronization of team structures to Slack, Figma, Linear, and popular engineering cohort platforms, matching your active payroll lists instantly.',
    category: 'Integrations'
  }
];

export default function FAQSection({ isDarkMode }: FAQSectionProps) {
  const [activeIndex, setActiveIndex] = useState<number | null>(0);
  const [searchQuery, setSearchQuery] = useState('');

  const filteredFAQs = FAQS.filter(faq => 
    faq.q.toLowerCase().includes(searchQuery.toLowerCase()) || 
    faq.a.toLowerCase().includes(searchQuery.toLowerCase()) ||
    faq.category.toLowerCase().includes(searchQuery.toLowerCase())
  );

  const toggleAccordion = (index: number) => {
    setActiveIndex(prev => prev === index ? null : index);
  };

  return (
    <section 
      id="faqs-accordion-section" 
      className={`py-24 relative select-none overflow-hidden border-b transition-colors duration-500 ${
        isDarkMode 
          ? 'bg-[#111111] border-stone-850' 
          : 'bg-white border-stone-100'
      }`}
    >
      {styleStyles()}
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10">
        
        {/* Adaptive Two-Column Layout */}
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-12 lg:gap-16 items-start">
          
          {/* Left Sticky Column wrapped with Scroll motion */}
          <motion.div 
            initial={{ opacity: 0, x: -30 }}
            whileInView={{ opacity: 1, x: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.7, ease: [0.16, 1, 0.3, 1] }}
            className="lg:col-span-5 text-left lg:sticky lg:top-24 flex flex-col items-start"
          >
            
            {/* Elegant Display FAQ Header with monochrome bottom border */}
            <div className={`relative mb-8 pb-3 border-b-2 inline-block ${
              isDarkMode ? 'border-stone-800' : 'border-stone-300'
            }`}>
              <h2 className={`text-5xl sm:text-6xl font-light tracking-tight font-sans ${
                isDarkMode ? 'text-white' : 'text-stone-900'
              }`}>
                FAQ
              </h2>
            </div>

            {/* Dynamic, polished descriptive paragraphs */}
            <h3 className={`text-lg sm:text-xl font-medium leading-relaxed mb-6 font-sans ${
              isDarkMode ? 'text-stone-300' : 'text-stone-800'
            }`}>
              We've put together the most common questions we get asked about global compliance, active contractor schemas, or Aura.
            </h3>

            <p className={`text-sm sm:text-base leading-relaxed mb-8 ${
              isDarkMode ? 'text-stone-400' : 'text-stone-550'
            }`}>
              If you have a question that you can't find here, please contact us directly for more information.
            </p>

            {/* Aesthetic Contact Us pill outline button exactly matching layout bounds & wide tracking */}
            <button
              id="btn-faq-contact-us"
              className={`px-8 py-3.5 rounded-full border text-[10px] tracking-[0.2em] font-extrabold uppercase transition-all duration-300 active:scale-[0.98] cursor-pointer ${
                isDarkMode
                  ? 'bg-transparent text-stone-200 border-stone-800 hover:text-white hover:border-stone-500 hover:bg-stone-900/30'
                  : 'bg-transparent text-stone-700 border-stone-300 hover:text-stone-950 hover:border-stone-950 hover:bg-stone-50'
              }`}
            >
              Contact Us
            </button>

            {/* Sub-aligned Minimal Search Box to filter FAQ nodes efficiently */}
            <div className="w-full max-w-sm mt-12 relative">
              <div className="absolute inset-y-0 left-0 pl-3.5 flex items-center pointer-events-none text-stone-500">
                <Search className="w-4 h-4 text-stone-400" />
              </div>
              <input
                type="text"
                placeholder="Search active FAQ criteria..."
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                className={`w-full pl-10 pr-4 py-2.5 rounded-xl text-xs font-semibold border outline-none focus:ring-1 transition-all ${
                  isDarkMode 
                    ? 'bg-stone-950/60 border-stone-805 text-stone-200 focus:ring-stone-600 focus:border-stone-600 placeholder-stone-605' 
                    : 'bg-stone-50 border-stone-200 text-stone-800 focus:ring-stone-400 focus:border-stone-400 placeholder-stone-400'
                }`}
              />
            </div>

          </motion.div>

          {/* Right Column Accordion List wrapped with stagger motion */}
          <motion.div 
            initial={{ opacity: 0, x: 30 }}
            whileInView={{ opacity: 1, x: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.8, ease: [0.16, 1, 0.3, 1] }}
            className="lg:col-span-7 flex flex-col w-full"
          >
            <div className={`border-t ${isDarkMode ? 'border-stone-850' : 'border-stone-200'}`}>
              {filteredFAQs.length > 0 ? (
                filteredFAQs.map((faq, index) => {
                  const isOpen = activeIndex === index;
                  return (
                    <div
                      key={index}
                      className={`border-b transition-all duration-300 ${
                        isDarkMode ? 'border-stone-850' : 'border-stone-200'
                      }`}
                    >
                      {/* Trigger Header Row */}
                      <button
                        onClick={() => toggleAccordion(index)}
                        className="w-full py-6 pr-2 flex items-center justify-between text-left gap-6 cursor-pointer select-none group"
                      >
                        <div className="flex flex-col gap-1.5 text-left">
                          <span className={`text-[9px] font-mono tracking-widest uppercase font-bold select-none ${
                            isDarkMode ? 'text-white' : 'text-stone-500'
                          }`}>
                            {faq.category}
                          </span>
                          <h4 className={`text-sm sm:text-base font-semibold group-hover:text-stone-500 dark:group-hover:text-white transition-colors leading-snug font-sans ${
                            isDarkMode ? 'text-stone-100' : 'text-stone-900'
                          }`}>
                            {faq.q}
                          </h4>
                        </div>

                        {/* Thin clean interactive Plus/Minus indicator with smooth rotation */}
                        <div className="w-6 h-6 flex items-center justify-center shrink-0">
                          <motion.div
                            animate={{ rotate: isOpen ? 180 : 0 }}
                            transition={{ duration: 0.3, ease: 'easeInOut' }}
                          >
                            {isOpen ? (
                              <Minus className={`w-4 h-4 stroke-[1.5] ${
                                isDarkMode ? 'text-white' : 'text-stone-900'
                              }`} />
                            ) : (
                              <Plus className={`w-4 h-4 stroke-[1.5] ${
                                isDarkMode ? 'text-stone-400 group-hover:text-white' : 'text-stone-550 group-hover:text-stone-900'
                              }`} />
                            )}
                          </motion.div>
                        </div>
                      </button>

                      {/* Expandable answer container with Framer Motion Layout heights */}
                      <AnimatePresence initial={false}>
                        {isOpen && (
                          <motion.div 
                            initial={{ height: 0, opacity: 0 }}
                            animate={{ height: "auto", opacity: 1 }}
                            exit={{ height: 0, opacity: 0 }}
                            transition={{ duration: 0.3, ease: [0.16, 1, 0.3, 1] }}
                            className="overflow-hidden"
                          >
                            <p className={`text-xs sm:text-sm leading-relaxed font-sans pr-4 pb-6 ${
                              isDarkMode ? 'text-stone-305' : 'text-stone-605'
                            }`}>
                              {faq.a}
                            </p>
                          </motion.div>
                        )}
                      </AnimatePresence>
                    </div>
                  );
                })
              ) : (
                <div className={`p-8 text-center border-b text-xs ${
                  isDarkMode ? 'border-stone-850 text-stone-500' : 'border-stone-200 text-stone-500'
                }`}>
                  No answers matching "{searchQuery}" could be located in our standard schemas. Try searching for "shield" or "EOR".
                </div>
              )}
            </div>
          </motion.div>

        </div>

      </div>
    </section>
  );
}

function styleStyles() {
  return (
    <style>{`
      #faqs-accordion-section, 
      #faqs-accordion-section h2, 
      #faqs-accordion-section h3, 
      #faqs-accordion-section h4, 
      #faqs-accordion-section p, 
      #faqs-accordion-section button, 
      #faqs-accordion-section span,
      #faqs-accordion-section input {
        font-family: 'Proxima Nova', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif !important;
      }
    `}</style>
  );
}
